// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-88w3tZL2P3fyZj_qvjZV_suMrpt4ui4',
    appId: '1:901856996962:web:0a435944f85eb0aa7eab3b',
    messagingSenderId: '901856996962',
    projectId: 'aroma-945aa',
    authDomain: 'aroma-945aa.firebaseapp.com',
    databaseURL: 'https://aroma-945aa-default-rtdb.firebaseio.com',
    storageBucket: 'aroma-945aa.firebasestorage.app',
    measurementId: 'G-EZQ6PC11VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrOUDc1kBDNxiBbCmBN6hXyXqsIt56Ko',
    appId: '1:901856996962:android:9a64fbce30d850b47eab3b',
    messagingSenderId: '901856996962',
    projectId: 'aroma-945aa',
    databaseURL: 'https://aroma-945aa-default-rtdb.firebaseio.com',
    storageBucket: 'aroma-945aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFm_aQj_ng_igKI9rGqnHDG_CABNXA8Wg',
    appId: '1:901856996962:ios:e13c87e5785d84887eab3b',
    messagingSenderId: '901856996962',
    projectId: 'aroma-945aa',
    databaseURL: 'https://aroma-945aa-default-rtdb.firebaseio.com',
    storageBucket: 'aroma-945aa.firebasestorage.app',
    iosBundleId: 'com.aroma.teacafe.aroma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFm_aQj_ng_igKI9rGqnHDG_CABNXA8Wg',
    appId: '1:901856996962:ios:e13c87e5785d84887eab3b',
    messagingSenderId: '901856996962',
    projectId: 'aroma-945aa',
    databaseURL: 'https://aroma-945aa-default-rtdb.firebaseio.com',
    storageBucket: 'aroma-945aa.firebasestorage.app',
    iosBundleId: 'com.aroma.teacafe.aroma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-88w3tZL2P3fyZj_qvjZV_suMrpt4ui4',
    appId: '1:901856996962:web:4a0cb8a8b4fe98587eab3b',
    messagingSenderId: '901856996962',
    projectId: 'aroma-945aa',
    authDomain: 'aroma-945aa.firebaseapp.com',
    databaseURL: 'https://aroma-945aa-default-rtdb.firebaseio.com',
    storageBucket: 'aroma-945aa.firebasestorage.app',
    measurementId: 'G-FMXZSD70XM',
  );
}
